apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: velero
  namespace: default
spec:
  interval: 5m
  chart:
    spec:
      chart: vmware-tanzu/velero
      version: '4.0.x'
      sourceRef:
        kind: HelmRepository
        name: vmware-tanzu
        namespace: flux-system
      interval: 1m
  values:
    replicaCount: 2